### ISSUE TITLE
Is python-tk actually needed?

### ISSUE THREAD

**Issue by jafingerhut** [p4pktgen/p4pktgen#129]
I know I was the one that created the tools/install.sh script, so I suspect that at least at the time I did, the python-tk Ubuntu package was needed for something, but I do not recall for what.

On Ubuntu 20.04 systems, installing python-tk depends upon, and so installs, Python2.7, which I believe nothing else in p4pktgen uses any more.

If we need something in python3-tk, we could install that instead, but not sure we do.  I may try a test run of p4pktgen on a freshly installed Ubuntu20.04 and 18.04 system with no Python2, both without python-tk and without python3-tk, to see if the tests pass, or if they need python3-tk for something.  I suspect they do not.

**Comment by iand-xilinx** [comment]
Fixed by Andy's #130.
